# Change these first
owner: aposudevsky # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Personal website
    url: https://aposudevsky.com
  - name: Avayly
    url: https://avayly.com

assignees: aposudevsky

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://www.avayly.com/img/avayly-2.png
  name: Avayly website monitoring
  introTitle: "Avayly website monitoring"
  introMessage: See below how our websites perform
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
